[2025-07-13T16:06:01.838+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T16:06:01.859+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data manual__2025-07-13T16:05:57.643999+00:00 [queued]>
[2025-07-13T16:06:01.868+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data manual__2025-07-13T16:05:57.643999+00:00 [queued]>
[2025-07-13T16:06:01.869+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T16:06:01.882+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): split_and_save_data> on 2025-07-13 16:05:57.643999+00:00
[2025-07-13T16:06:01.895+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=637) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-13T16:06:01.897+0000] {standard_task_runner.py:72} INFO - Started process 642 to run task
[2025-07-13T16:06:01.897+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'employee_ingestion_dag', 'split_and_save_data', 'manual__2025-07-13T16:05:57.643999+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_pipeline.py', '--cfg-path', '/tmp/tmp3k2cooun']
[2025-07-13T16:06:01.898+0000] {standard_task_runner.py:105} INFO - Job 339: Subtask split_and_save_data
[2025-07-13T16:06:01.963+0000] {task_command.py:467} INFO - Running <TaskInstance: employee_ingestion_dag.split_and_save_data manual__2025-07-13T16:05:57.643999+00:00 [running]> on host a0a54bfbbb9e
[2025-07-13T16:06:02.058+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_ingestion_dag' AIRFLOW_CTX_TASK_ID='split_and_save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T16:05:57.643999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-13T16:05:57.643999+00:00'
[2025-07-13T16:06:02.059+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T16:06:02.583+0000] {logging_mixin.py:190} INFO - Processing file: employee_data_with_errors_chunk_4.csv
[2025-07-13T16:06:02.583+0000] {logging_mixin.py:190} INFO - Total rows: 91, Invalid rows: 91
[2025-07-13T16:06:02.588+0000] {logging_mixin.py:190} INFO - File moved to bad_data: /opt/airflow/data/bad_data/employee_data_with_errors_chunk_4.csv
[2025-07-13T16:06:02.591+0000] {logging_mixin.py:190} INFO - Original file removed: /opt/airflow/data/raw_data/employee_data_with_errors_chunk_4.csv
[2025-07-13T16:06:02.591+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-13T16:06:02.606+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T16:06:02.606+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=employee_ingestion_dag, task_id=split_and_save_data, run_id=manual__2025-07-13T16:05:57.643999+00:00, execution_date=20250713T160557, start_date=20250713T160601, end_date=20250713T160602
[2025-07-13T16:06:02.674+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-13T16:06:02.692+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T16:06:02.694+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
