[2025-07-13T10:38:20.572+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T10:38:20.599+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data manual__2025-07-13T10:38:11.108781+00:00 [queued]>
[2025-07-13T10:38:20.613+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data manual__2025-07-13T10:38:11.108781+00:00 [queued]>
[2025-07-13T10:38:20.615+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T10:38:20.634+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): split_and_save_data> on 2025-07-13 10:38:11.108781+00:00
[2025-07-13T10:38:20.649+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=162) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-13T10:38:20.650+0000] {standard_task_runner.py:72} INFO - Started process 167 to run task
[2025-07-13T10:38:20.652+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'employee_ingestion_dag', 'split_and_save_data', 'manual__2025-07-13T10:38:11.108781+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_pipeline.py', '--cfg-path', '/tmp/tmp78pmu9y8']
[2025-07-13T10:38:20.655+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask split_and_save_data
[2025-07-13T10:38:20.791+0000] {task_command.py:467} INFO - Running <TaskInstance: employee_ingestion_dag.split_and_save_data manual__2025-07-13T10:38:11.108781+00:00 [running]> on host c45a93548ada
[2025-07-13T10:38:20.918+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_ingestion_dag' AIRFLOW_CTX_TASK_ID='split_and_save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T10:38:11.108781+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-13T10:38:11.108781+00:00'
[2025-07-13T10:38:20.920+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T10:38:21.480+0000] {logging_mixin.py:190} INFO - Processing file: employee_data_with_errors_chunk_5.csv
[2025-07-13T10:38:21.481+0000] {logging_mixin.py:190} INFO - Total rows: 88, Invalid rows: 88
[2025-07-13T10:38:21.486+0000] {logging_mixin.py:190} INFO - File moved to bad_data: /opt/airflow/data/bad_data/employee_data_with_errors_chunk_5.csv
[2025-07-13T10:38:21.489+0000] {logging_mixin.py:190} INFO - Original file removed: /opt/airflow/data/raw_data/employee_data_with_errors_chunk_5.csv
[2025-07-13T10:38:21.490+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-13T10:38:21.504+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T10:38:21.505+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=employee_ingestion_dag, task_id=split_and_save_data, run_id=manual__2025-07-13T10:38:11.108781+00:00, execution_date=20250713T103811, start_date=20250713T103820, end_date=20250713T103821
[2025-07-13T10:38:21.595+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-13T10:38:21.614+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T10:38:21.616+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
