[2025-07-13T11:29:04.113+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T11:29:04.131+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data scheduled__2025-07-13T11:28:00+00:00 [queued]>
[2025-07-13T11:29:04.140+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_ingestion_dag.split_and_save_data scheduled__2025-07-13T11:28:00+00:00 [queued]>
[2025-07-13T11:29:04.141+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-13T11:29:04.152+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): split_and_save_data> on 2025-07-13 11:28:00+00:00
[2025-07-13T11:29:04.159+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-13T11:29:04.161+0000] {standard_task_runner.py:72} INFO - Started process 232 to run task
[2025-07-13T11:29:04.161+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'employee_ingestion_dag', 'split_and_save_data', 'scheduled__2025-07-13T11:28:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/ingestion_pipeline.py', '--cfg-path', '/tmp/tmp9c2gne8o']
[2025-07-13T11:29:04.162+0000] {standard_task_runner.py:105} INFO - Job 214: Subtask split_and_save_data
[2025-07-13T11:29:04.218+0000] {task_command.py:467} INFO - Running <TaskInstance: employee_ingestion_dag.split_and_save_data scheduled__2025-07-13T11:28:00+00:00 [running]> on host a0a54bfbbb9e
[2025-07-13T11:29:04.346+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_ingestion_dag' AIRFLOW_CTX_TASK_ID='split_and_save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T11:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-13T11:28:00+00:00'
[2025-07-13T11:29:04.349+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T11:29:04.913+0000] {logging_mixin.py:190} INFO - Processing file: employee_data_with_errors_chunk_1.csv
[2025-07-13T11:29:04.915+0000] {logging_mixin.py:190} INFO - Total rows: 100, Invalid rows: 100
[2025-07-13T11:29:04.922+0000] {logging_mixin.py:190} INFO - File moved to bad_data: /opt/airflow/data/bad_data/employee_data_with_errors_chunk_1.csv
[2025-07-13T11:29:04.924+0000] {logging_mixin.py:190} INFO - Original file removed: /opt/airflow/data/raw_data/employee_data_with_errors_chunk_1.csv
[2025-07-13T11:29:04.925+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-13T11:29:04.946+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T11:29:04.946+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=employee_ingestion_dag, task_id=split_and_save_data, run_id=scheduled__2025-07-13T11:28:00+00:00, execution_date=20250713T112800, start_date=20250713T112904, end_date=20250713T112904
[2025-07-13T11:29:05.018+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-13T11:29:05.034+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T11:29:05.036+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
